user_name: "username"
password: "password"
sharepoint_base_url: "https://spe.web.sharepoint.ob.com"
sharepoint_pdf_url: "https://spe.web.sharepoint.ob.com/_api/web/GetFolderByServerRelativeUrl('%2FShared%20Documents%2FTRAI%2Fpdf')/Files/"
verify_cert: "/etc/pki/tls/certs/ob-chains.pem"

# Set to true to ingest PDFs from local file system instead of SharePoint.
upload_from_local: False

# If uploading from local, the folder containing the PDF files.
local_pdf_path: "/local/scratch/"

# Threshold (in months) to reingest a file if it was ingested before.
reingest_threshold_months: 4

pdf_entries:
  - filename: "FIRMWIDE STANDARD GLOBAL CLOUD GOVERNANCE_FINAL_10-Aug-2021_(v4.0).pdf"
    native_id: "DRO_firmwide_standard_0001"
    metadata: 
      title: "FIRMWIDE STANDARD Global Cloud Governance"
      sourceName_s: "TR-Advisory"
      sourceDomain_s: "Internal"
      sourceOriginDivision_s: "Technology Risk"
      fileFormat_s: "pdf"
      category_s: "Standard"
      lastUpdated_d: "2021-08-10"
      keywords_s: ["standard", "global", "cloud", "governance", "cloud infrastructure", "IaaS", "PaaS", "SaaS"]
      securityFramework_s: []
      securityControl_s: []
      reviewCadence_s: ""
      useCase_s: "Q&A"
  - filename: "FIRMWIDE POLICY ON PRIVACY_PROTECTION OF PERSONAL DATA_FINAL_01-Mar-2023_(v19.1).pdf"
    native_id: "DRO_firmwide_standard_0002"
    metadata:
      title: "Firmwide Policy on Privacy: Protection of Personal Data"
      sourceName_s: "TR-Advisory"
      sourceDomain_s: "Internal"
      sourceOriginDivision_s: "Technology Risk"
      fileFormat_s: "pdf"
      category_s: "Standard"
      lastUpdated_d: "2023-03-01"
      keywords_s: ["Privacy", "Policy", "Personal data security", "Unauthorized Disclosures", "Personal Data Usage"]
      securityFramework_s: []
      securityControl_s: []
      reviewCadence_s: ""
      useCase_s: "Q&A"
  - filename: "FIRMWIDE STANDARD ON IDENTITY MANAGEMENT FOR INTERNAL APPLICATIONS_FINAL_23-Nov-2022_(v6.2).pdf"
    native_id: "DRO_firmwide_standard_0003"
    metadata:
      title: "FIRMWIDE STANDARD ON IDENTITY MANAGEMENT FOR INTERNAL APPLICATIONS"
      sourceName_s: "TR-Advisory"
      sourceDomain_s: "Internal"
      sourceOriginDivision_s: "Technology Risk"
      fileFormat_s: "pdf"
      category_s: "Policy"
      lastUpdated_d: "2023-11-23"
      keywords_s: ["Identity Management", "Internal Applications", "Assets", "Identity", "Controls"]
      securityFramework_s: []
      securityControl_s: []
      reviewCadence_s: ""
      useCase_s: "Q&A"
  - filename: "Client Security Statement.pdf"
    native_id: "DRO_QA_0001"
    metadata:
      title: "Client Security Statement"
      sourceName_s: "TR-AWM"
      sourceDomain_s: "Internal"
      sourceOriginDivision_s: "Technology Risk"
      fileFormat_s: "pdf"
      category_s: "Report"
      lastUpdated_d: "2023-01-05"
      keywords_s: ["best practices", "governance", "audit", "asset management", "training", "Identity and Access Management"]
      securityFramework_s: []
      securityControl_s: []
      reviewCadence_s: "annual"
      useCase_s: "Q&A"

# Environment-specific Lex API endpoints
environments:
  dev:
    lex_ingest_url: "https://dev.genai.site.ob.com/ingestion/v1/tech_risk_ai/ingest"
    lex_search_url: "https://dev.genai.site.ob.com/search/v1/search/query"
    lex_delete_url: "https://dev.genai.site.ob.com/ingestion/v1/tech_risk_ai/nativeId"
    lex_status_url: "https://dev.genai.site.ob.com/ingestion/v1/status/tech_risk_ai/"
  qa:
    lex_ingest_url: "https://qa.genai.site.ob.com/ingestion/v1/tech_risk_ai/ingest"
    lex_search_url: "https://qa.genai.site.ob.com/search/v1/search/query"
    lex_delete_url: "https://qa.genai.site.ob.com/ingestion/v1/tech_risk_ai/nativeId"
    lex_status_url: "https://qa.genai.site.ob.com/ingestion/v1/status/tech_risk_ai/"
  prod:
    lex_ingest_url: "https://prod.genai.site.ob.com/ingestion/v1/tech_risk_ai/ingest"
    lex_search_url: "https://prod.genai.site.ob.com/search/v1/search/query"
    lex_delete_url: "https://prod.genai.site.ob.com/ingestion/v1/tech_risk_ai/nativeId"
    lex_status_url: "https://prod.genai.site.ob.com/ingestion/v1/status/tech_risk_ai/"

FIS:
  submission_url: https://uat.techrisk.fileinspection.site.ob.com/api/3.0/submissions
  FIS_api_key: "ZGV2X23ByYW5hbH10aWNz"
